server:
  port: 8080

spring:
  profiles:
    # 多个配置文件引入
    include:
      - custom
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms

# 支持打印 debug 日志
logging:
  level:
    cn.eastx.practice.demo.cache: debug

# Memcached 配置
mc:
  host: 127.0.0.1
  port: 11211